[project]
name = "synthds-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kafka-python>=2.0.6",
    "numpy>=2.2.3",
    "pandas>=2.2.3",
]
